eureka-server:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    port: ${EUREKA_INSTANCE_PORT:8070}
server:
  port: 8072
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
management:
  endpoint:
    gateway:
      access: read-only
      actuator:
        enabled: true
    routes:
      access: read-only
      actuator:
        enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,info,health,routes
  server:
    port: 9072
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka-server.instance.hostname}:${eureka-server.instance.port}/eureka/
