eureka-server:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    port: ${EUREKA_INSTANCE_PORT:8070}
kafka:
  instance:
    hostname: ${KAFKA_INSTANCE_HOSTNAME:localhost}
    port: ${KAFKA_INSTANCE_PORT:9092}
mail:
  instance:
    hostname: ${MAIL_INSTANCE_HOSTNAME:localhost}
    port: ${MAIL_INSTANCE_PORT:1025}
server:
  port: 8081
swagger-ui:
  url: "http://localhost:8081/swagger-ui/index.html"
springdoc:
  api-docs:
    path: /api-docs
spring:
  kafka:
    bootstrap-servers: ${kafka.instance.hostname}:${kafka.instance.port}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      security:
        protocol: PLAINTEXT
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer-class-config: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000
      properties:
        spring:
          json:
            trusted:
              packages: org.example.kafka.dto
      security:
        protocol: PLAINTEXT
    listener:
      poll-timeout: 3000
      type: single
      concurrency: 3
  mail:
    host: ${mail.instance.hostname}
    port: ${mail.instance.port}
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka-server.instance.hostname}:${eureka-server.instance.port}/eureka/
